repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=8192]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--allow-multiple-documents]
      exclude: "conda.recipe/meta.yaml"
    - id: end-of-file-fixer
      exclude: "nucDataLibs/.*"
    - id: trailing-whitespace
      exclude: "nucDataLibs/.*"
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: "nucDataLibs/.*"
    - id: ruff-format
      exclude: "nucDataLibs/.*"
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      exclude: "(nucDataLibs/.*|.*\\.ipynb)|poetry.lock"
      args: ["--ignore-words-list=DELTE"]
