repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=8192]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--allow-multiple-documents]
      exclude: "conda.recipe/meta.yaml"
    - id: end-of-file-fixer
      exclude: "(tests/data/.*|src/pleiades/data/.*)"
    - id: trailing-whitespace
      exclude: "(tests/data/.*|src/pleiades/data/.*)"
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: "(tests/data/.*|legacy/.*|src/pleiades/data/.*)"
    - id: ruff-format
      exclude: "(tests/data/.*|legacy/.*|src/pleiades/data/.*)"
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      exclude: "(tests/data/.*|.*\\.ipynb|pixi.lock|src/pleiades/data/.*)"
      args: ["--ignore-words-list=DELTE"]
